spring.application.name=Copy_MGL_Local


logging.level.org.springframework.web=debug
server.port=8080
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.allowed-methods=POST,GET,PATCH,PUT
management.trace.http.enabled=true


# Old Credentials
#salesforce.token-url=https://site-efficiency-1388--mglintegr.sandbox.my.salesforce-setup.com/services/oauth2/token
#salesforce.grant-type=password

#salesforce.username=integrationuser@mglintegr.com
#salesforce.instance-url=https://site-efficiency-1388--mglintegr.sandbox.my.salesforce-setup.com
#salesforce.password=MGL@2025


# New Credentials
salesforce.token-url=https://site-efficiency-1388--mglintegr.sandbox.my.salesforce-setup.com/services/oauth2/token
salesforce.grant-type=password

salesforce.client-id=3MVG9Wr8x2TEhDdL_iDXaLQBCJzu27jMHPlVMCOZ3ctW0i9kz1T51jo8AFnPTy5ZGJnV8k6CJYaomhnkq1KWV
salesforce.client-secret=BA4E7D87717BF35AC83669531612E7E101C605B5D08C7E04B34AA9FD3924524D

salesforce.username=integrationuser@mglintegr.com
salesforce.instance-url=https://site-efficiency-1388--mglintegr.sandbox.my.salesforce-setup.com
salesforce.password=MGL@2025


logging.level.root=INFO
logging.level.com.example=DEBUG



tubelight.plain-url=https://webpostservice.com/sendsms_v2.0/sendsms.php
tubelight.unicode-url=https://webpostservice.com/sendsms/sendsms.php
tubelight.bulk-url=https://webpostservice.com/sendsms_v1.0/chakra.php
tubelight.balance-url=https://webpostservice.com/sendsms/checkbalance.php
tubelight.delivery-status-url=https://webpostservice.com/sendsms/dlrstatus.php

tubelight.type.text=TEXT
tubelight.type.flash=FLASH
tubelight.type.unicode=UNICODE
tubelight.type.unicode-flash=UNICODE-FLASH

tubelight.username=mglsf
tubelight.password=5o94V3iu
tubelight.sender.id=TLIGHT
tubelight.mobile=9865392511
tubelight.type=TEXT







  



